### ISSUE TITLE
英語のヘッダメニューのタイトルがTokyoになっている

### ISSUE THREAD

**Issue by kitadakyou** [CodeForNagasaki/covid19#132]
## 起こっている問題 / The Problem
- 言語を英語にした際、ヘッダーのタイトルが "Tokyo COVID-19 Information" になっている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/4303909/78868978-cbb00580-7a7e-11ea-9a51-8734ecd7bb71.png)

## 期待する見せ方・挙動 / Expected Behavior
- Tokyo を Nagasaki に修正

## 動作環境・ブラウザ / Environment
- 全て

**Comment by kensukekanzaki** [comment]
kitadakyouさんありがとうございますー。

**Comment by sugasaki** [comment]
@kitadakyou 
ほんとだ、英語版まったくチェックしてなかったので気づいてなかったです。
こうなった日本語表記に「長崎」って入ってないのもどうなんだろう？って思いますね。

**Comment by sugasaki** [comment]
<img width="353" alt="スクリーンショット 2020-04-09 20 37 13" src="https://user-images.githubusercontent.com/1316886/78891154-eb0c5a00-7aa1-11ea-903b-9b828b29eb83.png">

東京都も入ってないから、現状ままでいいですかね
