### ISSUE TITLE
陽性患者の属性カード/更新日の表示が[object Object]になってる

### ISSUE THREAD

**Issue by kensukekanzaki** [CodeForNagasaki/covid19#134]
## 起こっている問題 / The Problem
陽性患者の属性カードの更新日の表示がエラー。

## スクリーンショット / Screenshot
<img width="610" alt="スクリーンショット 2020-04-09 19 45 11" src="https://user-images.githubusercontent.com/62322626/78887580-1770a800-7a9b-11ea-8d54-9dd2fb4344ba.png">

## 期待する見せ方・挙動 / Expected Behavior
更新日がきちんと表示されるようにしたい

**Comment by kensukekanzaki** [comment]
改善させます。

**Comment by sugasaki** [comment]
ありがとうございます。
そうなんです。すごく気になってたけど後回しにしてしまってて
