### ISSUE TITLE
帰国者接触者相談センターの更新を押すと何も表示されなくなる（PC版）

### ISSUE THREAD

**Issue by sugasaki** [CodeForNagasaki/covid19#138]
## 起こっている問題 / The Problem
- 更新をクリックするとまっしろ画面になる

## スクリーンショット / Screenshot

| action1 | result |
| ------- | ------ |
| <img width="1115" alt="スクリーンショット 2020-04-09 21 52 27" src="https://user-images.githubusercontent.com/1316886/78897022-7b4f9c80-7aac-11ea-9422-859f443b4fc4.png"> | <img width="1208" alt="スクリーンショット 2020-04-09 21 54 04" src="https://user-images.githubusercontent.com/1316886/78897153-b356df80-7aac-11ea-9773-3d27dab7d323.png"> | 

## 期待する見せ方・挙動 / Expected Behavior
- 他のカードのように単体表示できるようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. 帰国者接触者相談センターの更新をクリックする
2. 切り替わった画面を眺める

切り替わった画面のURLは以下である。

https://nagasaki.stopcovid19.jp/cards/health-center

**Comment by tkt989** [comment]
やります！

**Comment by sugasaki** [comment]
@tkt989 ありがとうございます！
