### ISSUE TITLE
アイキャッチ画像を変更する

### ISSUE THREAD

**Issue by sugasaki** [CodeForNagasaki/covid19#139]
## 改善詳細 / Details of Improvement
- アイキャッチ画像を変更する

## スクリーンショット / Screenshot

<img width="1494" alt="スクリーンショット 2020-04-10 21 51 43" src="https://user-images.githubusercontent.com/1316886/78992283-d7322800-7b75-11ea-90be-7b0a13ced6dd.png">

## 期待する見せ方・挙動 / Expected behavior
- README.MDのイラスト差し替え
- Aboutのイラスト差し替え
− 作者情報の追加
− 作者のイラストに込める思い
− キャラの設定など追加

## 作者情報へのりんく
- Twitter
https://twitter.com/pinografico

- HP (HTTPS)
https://pinografi.com

- クレジット表記
MATSUMOTO RYOTA

**Comment by kensukekanzaki** [comment]
対応します

**Comment by sugasaki** [comment]
@kensukekanzaki
まつもとさんから連絡あり、
以下とのことです。

```
クレジットが「まつもとりょうた」と日本語でしたが、英語に統一でお願いします

MATSUMOTO RYOTA

```

**Comment by sugasaki** [comment]
画像についての説明をイラスト下部に追記したいですね。
イラスト作者の言葉

> 長崎県を表現する際に、「歴史」をベースにしました。
> 人物は、「勝利の女神」的な設定で、表情は男っぽくして、性別は限定させず受け取る人の感性に任せるようにしました。（女性にしか見えないかもしれませんが。。笑）
> 
> 羽織っているコートは阿蘭陀カピタンのものをイメージし、普段は疫病から自身を守るため仮面と布で顔を覆っているのですが、激しい戦いに顔が見えている状態です。ブーツは坂本龍馬をリスペクトしている表現です。
> 
> 仮面はジャカルタから伝えられたと言われる「おまがり猫」の面の設定。
> 
> 望遠鏡・・・情報を常に収集し
> 手の包帯・・・菌を直接触れないための防護
> ひょうたん・・・除菌用
> 日本刀・・・戦う意志
> 
> 現代に生まれた過去の偉人を象徴する存在としました。
> 
> ご指摘のとおり、龍馬も四郎も的を得ているかもしれませんね！
> カピタン、龍馬、四郎　というところでしょうか。
> 県全体を表現するため、設定を明確にはしなかったというところです。

**Comment by sugasaki** [comment]
キャラ設定

> 長崎を舞台に活躍した偉人、阿蘭陀カピタンと坂本龍馬の魂が蘇ったと言われる、疫病と戦う一人の若者。
> 常に猫の仮面と更紗布で顔を覆い、その正体は明らかにされていなかった。
> 時世を見定める望遠鏡と大きな日本刀と消毒ひょうたんがこの若者の必需品。

**Comment by sugasaki** [comment]
絵に込めた思い


> 目に見えないコロナを相手に、
> 『しっかり正しい情報を得て（望遠鏡）、常に冷静な防護の姿勢で（仮面、布）、消毒（ひょうたん）を行おう』というメッセージをイラストのアイテムに込めました。
> 
> そして戦って日常を勝ち取るぞという希望を込めて一人の若者で表現しました。
> 「多くの世代に届くといいな」と念じながら長崎らしい歴史的なモチーフでカッコいいヒーローのような象徴を描きました。
