### ISSUE TITLE
検査実施件数グラフに不要な凡例を消したい

### ISSUE THREAD

**Issue by sugasaki** [CodeForNagasaki/covid19#151]
## 起こっている問題 / The Problem
- 検査実施件数グラフに不要な凡例がある

## スクリーンショット / Screenshot

<img width="549" alt="スクリーンショット 2020-04-10 19 47 02" src="https://user-images.githubusercontent.com/1316886/78985634-4272fe80-7b64-11ea-865f-a97e4af96950.png">

## 期待する見せ方・挙動 / Expected Behavior
- 不要な凡例消す

<img width="549" alt="スクリーンショット 2020-04-10 19 47 02" src="https://user-images.githubusercontent.com/1316886/78985680-5a4a8280-7b64-11ea-832a-59ab72b365e1.png">

**Comment by tkt989** [comment]
やります 🙋

**Comment by sugasaki** [comment]
おねがいします！！

**Comment by sugasaki** [comment]
`brigade/nagasaki/components/cards/TestedNumberCard.vue`の以下について補足します

`import TimeStackedBarChart from '@/brigade/nagasaki/components/TimeStackedBarChart.vue'`

本来は東京本家の/components/TimeStackedBarChart.vueをそのまま使いたかったのですが、
TimeStackedBarChart.vueが都内発生とその他の2つのデータがあるという前提で処理が組んであったので
`nagasaki/components/TimeStackedBarChart.vue` を作って凌いでます。
すごい冗長だと思ってます。

`nagasaki/components/TimeStackedBarChart.vue` を消せるならば消したいです

**Comment by tkt989** [comment]
情報ありがとうございます！
他拠点では`TimeStackedBarChart`の代わりに、`TimeBarChart`を使っているようなので、そっちでも試してみます。

大分県: https://github.com/covid19-oita/covid19/blob/development/components/cards/TestedNumberCard.vue#L3
福岡県: https://github.com/Code-for-Fukuoka/covid19-fukuoka/blob/development/pages/index.vue#L49

**Comment by sugasaki** [comment]
他拠点まで調べてもらってありがとうございます。
よろしくお願いしますm(_ _)m
