### ISSUE TITLE
長崎市の窓口混雑情報が月曜日(4/13)で終了　→ リンクを削除する

### ISSUE THREAD

**Issue by sugasaki** [CodeForNagasaki/covid19#157]
## 改善詳細 / Details of Improvement
- 長崎市の窓口混雑情報が月曜日(4/13)で終了になる。
- 対応は窓口情報が本当に削除されてからでOK

## スクリーンショット / Screenshot

<img width="332" alt="スクリーンショット 2020-04-11 21 05 50" src="https://user-images.githubusercontent.com/1316886/79043148-73246800-7c38-11ea-957d-bd63e210f2d9.png">

## 期待する見せ方・挙動 / Expected behavior
- リンクを削除する
- i18 ファイルからも情報削除する

**Comment by sugasaki** [comment]
4/13 で終了する旨記載されたので、リンク削除しましょうか

<img width="758" alt="スクリーンショット 2020-04-14 1 15 51" src="https://user-images.githubusercontent.com/1316886/79137366-8e84a400-7ded-11ea-9135-3137bffc79c2.png">

**Comment by tkt989** [comment]
もう404になってますね
削除します 🙋

**Comment by sugasaki** [comment]
ありがとうございます
お願いします！
