### ISSUE TITLE
言語翻訳ファイルを長崎版データで上書きする運用に変えたい

### ISSUE THREAD

**Issue by sugasaki** [CodeForNagasaki/covid19#159]
## 起こっている問題 / The Problem

**東京本家のデータが日々、小刻みに変更するので追従が辛い**

現在、言語翻訳ファイルを`/assets/locales/nagasaki/*.json`の下に配置し
東京本家の情報`/assets/locales/*.json`は参照していない

東京本家に変更がある都度、`/assets/locales/nagasaki/*.json`を更新しているが、更新が辛い

## 期待する見せ方・挙動 / Expected Behavior
- 基本は東京本家の情報`/assets/locales/*.json`を参照する
- 長崎用言語翻訳ファイルを`/assets/locales/nagasaki/*.json`の下に配置し、上記を上書きする

**Comment by kitadakyou** [comment]
複数のファイルを参照することは [vue-i18n のドキュメント](https://kazupon.github.io/vue-i18n/guide/lazy-loading.html)を見た限り難しそうでした。。

現実的な落とし所として、

① `/assets/locales/nagasaki/*` の下は長崎独自の言語設定のみを記述
② `/assets/locals/*` は東京版をそのまま持ってくる
③ ビルド時に ①と②を concat したものを`/assets/locales/nagasaki/*`に設置
④参照は `/assets/locales/nagasaki/*` に向ける

のようなものを考えましたが、如何でしょうか？

**Comment by sugasaki** [comment]
なるほど！concatするって手がありましたね。
package.jsonの"scripts"に仕込むイメージでしょうか？

。。。返信遅くなってすみません。

**Comment by kitadakyou** [comment]
@sugasaki はい、それか GitHub Actions のビルド時に生成する(シェルスクリプトが使えるのでこちらの方が簡単？)のどちらかになると思います。

少し時間がかかるかもしれないですが、他の作業とコンフリクトすることはなさそうなので、Actions に仕込む形で私の方でやってみようと思います。

**Comment by sugasaki** [comment]
おぉぉぉっぉ、ありがとうございます。

ちょっと気になるのが、Actions に仕込んだ場合って、ローカルデバッグ時に気付きにくいんじゃないかなぁと思うんですがどうでしょう？

**Comment by kitadakyou** [comment]
@sugasaki 
確かに、デバッグについては考えていませんでした…
`generate_locales.sh` を `/brigade/nagasaki/tool/`  等に設置し、それを node-script 経由で実行するとデバッグしやすいですかね。
いや、シェルスクリプトファイルを用意した時点で、Actions から直接読んでも同じような気がしますが。。

**Comment by sugasaki** [comment]
package.jsonの`"scripts"`の`"dev":`の先頭らへんに`concat`を差し込んだら　`yarn dev` 時に毎回concatされるから間違いなくていいかなと思うんですが、どうでしょう？

**Comment by kitadakyou** [comment]
すみません、やっと分かりました。
デバッグ時にファイルを出力 → そのまま push ということですね。
理解が遅くて申し訳ありません。。

はい、それが一番確実だと思いますので、その方法で実装いたします！

**Comment by sugasaki** [comment]
で、こないだ提案していただいたものなんですが、

以下の２つを用意したとして

- `/assets/locales/ja.json`　←東京オリジナル
- `/assets/locales/nagasaki/ja.json`　←長崎（差分のみ）


concat の順番を入れ替えて、どっちかが先に結合さえると後勝ちで言語ファイルが上書きされないかなー？と
淡い期待してるんですが、どうでしょう？
もしこれが上書きされると、更新がすごく楽になるなーと

**Comment by sugasaki** [comment]
連投すみません。追記です。

> package.jsonの"scripts"の"dev":の先頭らへんにconcatを差し込

package.jsonの"scripts"の"dev":にShellスクリプトのファイルパスを入れとけばメンテは楽かもですね。

**Comment by kitadakyou** [comment]
@sugasaki こちらの想定では

- `/assets/locales/ja.json`　←東京オリジナル
- `/assets/locales/nagasaki/ja.json`　←長崎（差分のみ）

の2つを concat したものを

- `/assets/locales/nagasaki/_ja.json` ← 機械的に出力されるもの、編集禁止の旨をファイル先頭に記述

のような名前で出力し、`nuxt-i18n.nagasaki.config.ts` の参照をそちらに向けようかと考えていました。(上書きしてしまうと、運用事故が起きそうなので。。)

そうすれば、東京版はそのままマージすればよく、長崎版も必要な時に定義を追加していけば最終的なファイルは最新に保たれるのでいいかと思うのですが、如何でしょうか？

**Comment by sugasaki** [comment]
おぉ！
そうですそうです！！:clap:

すごくありがたいです。
ただ、無理せず、ぼちぼちのんびりやっていただけるとありがたいです。
急ぎませんので

**Comment by kitadakyou** [comment]
@sugasaki シェルスクリプトで JSON のキーを上書きするのがあまりにも分かりにくい書き方になったため、node.js を使う方法に変更しております。
それ以外は上記の仕様のままです。
