### ISSUE TITLE
新型コロナウイルス感染症が心配なときに > 印刷ページのQRコードが東京版になっている

### ISSUE THREAD

**Issue by sugasaki** [CodeForNagasaki/covid19#179]
## 起こっている問題 / The Problem
- 新型コロナウイルス感染症が心配なときに > 印刷ページのQRコードが東京版になっている

## スクリーンショット / Screenshot

<img width="742" alt="スクリーンショット 2020-04-13 20 29 10" src="https://user-images.githubusercontent.com/1316886/79117228-857fdc80-7dc5-11ea-897d-0cf29be596c3.png">

## 期待する見せ方・挙動 / Expected Behavior
- 以下のURLを参照するQRコードに変える

https://nagasaki.stopcovid19.jp/

## 起こっている問題の再現手段 / Steps to Reproduce
1. 新型コロナウイルス感染症が心配なときに
2. 印刷ボタンを押す

**Comment by sentakuhakase** [comment]
先走ってプルリクなげてしまいましたが、
QRコード生成してアップロードしました。

プル後にデプロイされたテストサイトから、印刷を行い、長崎県版に飛べる事は確認しました。

**Comment by sugasaki** [comment]
ありがとうございます！
