### ISSUE TITLE
検査実施件数グラフの幅が狭く表示される。（時々出現する）

### ISSUE THREAD

**Issue by sugasaki** [CodeForNagasaki/covid19#209]
## 起こっている問題 / The Problem
- 検査実施件数グラフの幅が狭いく表示される。（時々出現する）

## スクリーンショット / Screenshot

<img width="1197" alt="スクリーンショット 2020-04-16 12 54 34" src="https://user-images.githubusercontent.com/1316886/79412900-83926500-7fe1-11ea-861d-58e4a1d298ca.png">

<img width="547" alt="スクリーンショット 2020-04-16 12 53 08" src="https://user-images.githubusercontent.com/1316886/79412794-4d54e580-7fe1-11ea-8d47-054f41ccfc48.png">

## 期待する見せ方・挙動 / Expected Behavior
- 他のカードと同様のサイズで表示されるようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. indexページにアクセス

## 動作環境・ブラウザ / Environment
- macOS
- Safari

**Comment by kitadakyou** [comment]
CORS 制約でデータの取得に失敗して、その後の length を計算する処理でエラーになっていることが原因のようです。(本日分のデータが表示されていないのもそれが原因？)
恐らく、`callFetchJsonp` 関数内で Header を適切に設定してあげれば解消されると思われます。

ただ、私の `yarn dev` 環境で再現されないため、本当に直るか分からないのですが、どうしましょうか…？

![image](https://user-images.githubusercontent.com/4303909/79471235-54114600-803d-11ea-8d07-ac817113416c.png)

**Comment by sugasaki** [comment]
県のオープンデータサイトがallow-originの設定がないので、CORSの制約で非同期なfetchが失敗するという問題があってですね、（axiosやfetchではcorsの制約エラーで取れなかったです）
JSONPで取得しているのが現状です。

てっきりCORSの影響を受けてると思ってなかったので、うーん、まいったなぁと思ってます。

もしかしたら、検査実施件数カードのグラフ表示に使用するコンポーネントを`TimeStackedBarChart`から`TimeBarChartに`変更したので、可能性薄いけど、その線でも調査しようかなと思ってました

**Comment by sugasaki** [comment]
ちなみに、県のオープンデータサイトのサンプルに以下のようにあったので、
県の取得サンプルでもJSONPになってたので同様にしてます。
```
  var data = {
    resource_id: '71e83845-2648-4cb3-a69d-9f5f5412feb2', // the resource id
    limit: 5, // get 5 results
    q: 'jones' // query for 'jones'
  };
  $.ajax({
    url: 'http://data.bodik.jp/api/action/datastore_search',
    data: data,
    dataType: 'jsonp',
    success: function(data) {
      alert('Total results found: ' + data.result.total)
    }
  });
```

**Comment by tkt989** [comment]
サーバーサイドレンダリングで通っている`/pages/index.vue#fetch()`の非同期通信がクライアントサイドでも走っているようなので、`process.client`を使ってブラウザ上では通らないようにするのはどうでしょうか。

非同期通信をしている箇所、`fetch()`と`mounted()`で、

* `fetch()` -> axios (not jsonp)
* `mounted()` -> fetchJsonp

なのでブラウザで`fetch()`を通るとcorsになります。

**Comment by sugasaki** [comment]
なるほどですね。
それにしてもcorsエラーが起きても`if (!data) return` で抜けてstoreには保存されないからコンポーネントに影響を及ぼしてるのが、どうしてなんだろう？？という疑問が払拭されなくて。

**Comment by sugasaki** [comment]
ひとまず試行錯誤やってみます。

**Comment by kitadakyou** [comment]
すみません、返信遅くなりました。。
よろしくお願いいたします！

**Comment by sugasaki** [comment]
ローカル環境で`yarn run generate:deploy` として`/dist`にデプロイされたものをWebサーバーを通して実行したらこの問題がローカルでも再現できました。

で、`await $axios.get`を全てtryで囲ったら3つのCORSエラーが表示され状況変わらずでした。

<img width="1548" alt="スクリーンショット 2020-04-17 21 45 53" src="https://user-images.githubusercontent.com/1316886/79571412-1e7c6380-80f6-11ea-8fed-7324ea3d5c21.png">



その後、3つの`await $axios.get`をコメントアウトしたら、CORSエラーは消えましたがグラフが狭く表示されることは変わらずでした。
<img width="1166" alt="スクリーンショット 2020-04-17 21 51 56" src="https://user-images.githubusercontent.com/1316886/79571427-263c0800-80f6-11ea-9206-ba028c79ff1a.png">


もちっと調査進めます。

**Comment by sugasaki** [comment]
どうも、`this.$store.state.bodik1`が空[]の場合があるときにエラーになってました。
以下の行を追加しました。

```
const dumy = [{ 日付: '2020/3/1', 小計: 0 }]
const bodik = this.$store.state.bodik1
if (!bodik || bodik.length === 0) return formatGraph(dumy)
```

**Comment by tkt989** [comment]
修正ありがとうございます！ 🙇

**Comment by sugasaki-atsushi** [comment]
とんでもねーです。おかげで一歩すすみました。
こちらこそありがとうございます 🙇
