### ISSUE TITLE
Bodik APIに対してLimitを指定しない場合はデフォルト100件になっている

### ISSUE THREAD

**Issue by sugasaki** [CodeForNagasaki/covid19#236]
## 改善詳細 / Details of Improvement
- Bodik APIに対してLimitを指定しない場合はデフォルト100件になっている

以下の場合には100件しか取れない
http://data.bodik.jp/api/action/datastore_search?resource_id=71e83845-2648-4cb3-a69d-9f5f5412feb2

## 期待する見せ方・挙動 / Expected behavior
- limit=5000とか当分大丈夫なLimit値に変更する

http://data.bodik.jp/api/action/datastore_search?resource_id=71e83845-2648-4cb3-a69d-9f5f5412feb2&limit=5000

### 改善点
Fetch JSONPを使う際に、パラメータ渡しに変えたい

https://github.com/camsong/fetch-jsonp#set-jsonp-callback-parameter-name-default-is-callback

**Comment by tkt989** [comment]
やります 🙋

**Comment by sugasaki** [comment]
ありがとうございます
よろしくお願いします！
