### ISSUE TITLE
検査実施件数グラフを県内、県内以外（クルーズ船）と分けて表示する

### ISSUE THREAD

**Issue by sugasaki** [CodeForNagasaki/covid19#243]
## 改善詳細 / Details of Improvement
- 検査実施件数グラフを県内、県内以外（クルーズ船）と分けて表示する

## 期待する見せ方・挙動 / Expected behavior
以前の東京版のように分けて表示する

- 県内発生
- その他（チャーター船・クルーズ船等）

<img width="300" alt="スクリーンショット 2020-04-22 18 52 14" src="https://user-images.githubusercontent.com/1316886/79968138-ae415980-84ca-11ea-994f-fead555358fe.png">

## データ

開発用に以下のデータを使用する
完成したら、県庁の担当と調整し本番データを入れ替える。

### APIカタログサイト
https://data.bodik.jp/dataset/420000_prefnagasakicovidexamcruise/resource/660c1ea1-3ed6-44de-9a2e-407508cb23c2

### API
http://data.bodik.jp/api/action/datastore_search?resource_id=660c1ea1-3ed6-44de-9a2e-407508cb23c2&limit=1000

※ 年月日が/区切りから-区切りに変わります。（画像は/のままなので要注意）

<img width="872" alt="スクリーンショット 2020-04-22 19 23 03" src="https://user-images.githubusercontent.com/1316886/79971050-c7e4a000-84ce-11ea-896f-36ea3aa79834.png">

データ内の各列を以下のように扱う

- 件数： 県内発生のデータ
- 件数_その他： その他（チャーター船・クルーズ船等）

## 対応

TimeStackedBarChartを使うように切り替えたらうまくいくと思われる

**Comment by kitadakyou** [comment]
@sugasaki やってみようと思います

**Comment by sugasaki** [comment]
@kitadakyou 
ありがとうございますm(_ _)m
すごくすごく助かります

**Comment by sugasaki** [comment]
@kitadakyou 
以下のでTimeStackedBarChart　→　TimeBarChart　に変更してます。
https://github.com/CodeForNagasaki/covid19/commit/e2655292b478fe85ac008e939b65ce6a187ca1c6#diff-154c22a632ebdc2898cf7e60983931f6


TimeBarChart 　→　TimeStackedBarChart　にまた変更したらいいのかなとぼやっと思ってます。

**Comment by kitadakyou** [comment]
ありがとうございます！とりあえずグラフの表示までは行けました。
色々おかしいのでここから修正をしていきます…

![image](https://user-images.githubusercontent.com/4303909/79988368-89a8aa00-84e9-11ea-8832-f53d53440e24.png)

**Comment by sugasaki** [comment]
すごい！はやい！！
よろしくお願いします

**Comment by kitadakyou** [comment]
すみません、

- 陽性患者数のグラフがおかしくなってしまうこと
- 「テーブルを表示」した際のデータがおかしくなってしまうこと(どこのコンポーネントを参照しているのか分からず…)

が解決できずにおります。
原因が分かりますでしょうか…？

![image](https://user-images.githubusercontent.com/4303909/79991581-70a1f800-84ed-11ea-8b2b-23d82a85ef6c.png)
![image](https://user-images.githubusercontent.com/4303909/79991591-71d32500-84ed-11ea-8241-df8f471b8430.png)

**Comment by sugasaki** [comment]
これは、たぶん日付がハイフン区切りになった影響かもしれないです

**Comment by sugasaki** [comment]
陽性患者数のグラフは私が下のIssueで解決しましょうか
https://github.com/CodeForNagasaki/covid19/issues/244

**Comment by sugasaki** [comment]
>「テーブルを表示」した際のデータがおかしくなってしまうこと(どこのコンポーネントを参照しているのか分からず…)

これはこないだ東京版を取り込んだときに追加された機能なのですが、
まだ詳しくは機能を把握してなかったです。私も調べてみますね

**Comment by kitadakyou** [comment]
早速ありがとうございます！
2番目については変数名を間違えていた凡ミスでした…

![image](https://user-images.githubusercontent.com/4303909/79992758-e2c70c80-84ee-11ea-9bfe-ae825ff25852.png)

**Comment by kitadakyou** [comment]
> 陽性患者数のグラフは私が下のIssueで解決しましょうか

ありがとうございます、
あまり遅くなると申し訳ないので、一旦現状で PR を上げても宜しいでしょうか？

**Comment by sugasaki** [comment]
よろしくお願いしますm(_ _)m

**Comment by kitadakyou** [comment]
@sugasaki PR上げました。他におかしな所がないか確認します…

**Comment by sugasaki** [comment]
あざっす
