### ISSUE TITLE
英語化されてないとこを英語化したい

### ISSUE THREAD

**Issue by sugasaki** [CodeForNagasaki/covid19#265]
## 改善詳細 / Details of Improvement
- 英語化されてないとこを英語化したい

## スクリーンショット / Screenshot

<img width="1164" alt="スクリーンショット 2020-04-26 14 43 05" src="https://user-images.githubusercontent.com/1316886/80299049-4fcaf280-87cc-11ea-8d5d-ca4c723a0a60.png">

## 期待する見せ方・挙動 / Expected behavior
- 英語化したい

**Comment by bun913** [comment]
@sugasaki 
こちら私が対応させていただいても良いでしょうか？（今週中には対応できるかと思います）

**Comment by sugasaki** [comment]
@bun913 
ありがとうございます！
よろしくお願いいたします。（急がなくてもOKです）

**Comment by bun913** [comment]
@sugasaki 

一旦PRを作成いたしました。
ただしばらく待っているのですが CI/CDが終わらないので、先に関連PRをマージする必要があるでしょうか？

お手隙の際にご教示・レビューお願いいたします。

https://github.com/CodeForNagasaki/covid19/pull/361

**Comment by sugasaki** [comment]
@bun913 
PRありがとうございますm(_ _)m
ひさしぶりにPRを受けたのですかっと忘れてました。
初めてのPRには承認が必要だったみたいです。先ほどAPPROVEボタンをぽちっと押しました。
次からは大丈夫だと思います。

**Comment by sugasaki** [comment]
@bun913 
PRの方へもコメントしました。
