### ISSUE TITLE
（長崎市保健所）専用の電話番号になっていない

### ISSUE THREAD

**Issue by nagasakisijohosystem** [CodeForNagasaki/covid19#36]
## 起こっている問題 / The Problem
長崎市保健所の電話番号として地域保健課の代表番号が記載されている

## 期待する見せ方・挙動 / Expected Behavior
長崎市帰国者・接触者相談センターの専用番号を記載する
095-801-1712

**Comment by kensukekanzaki** [comment]
対応します。
