### ISSUE TITLE
検査陽性者の状況の注釈が都内のまま

### ISSUE THREAD

**Issue by nagasakisijohosystem** [CodeForNagasaki/covid19#37]
## 起こっている問題 / The Problem
検査陽性者の状況注釈の「県内」となっているべきところが「都内」となっている
![検査陽性者注釈](https://user-images.githubusercontent.com/62535540/77502802-3ff38200-6e9f-11ea-8161-bf91c2ab7602.jpg)

## 期待する見せ方・挙動 / Expected Behavior
「都内」を「県内」へ修正

**Comment by kensukekanzaki** [comment]
修正対応します。

**Comment by sugasaki** [comment]
@kensukekanzaki

表記がまだ変わってませんでした。
おそらく `components/SvgCard.vue`の以下部分も変えないとと思います。

`'（注）都内において疑い例または患者の濃厚接触者として検査を行ったものについて掲載'`
