### ISSUE TITLE
長崎市の最新情報表示用コンポーネントの追加

### ISSUE THREAD

**Issue by sugasaki** [CodeForNagasaki/covid19#43]
## 改善詳細 / Details of Improvement

- 長崎市の最新情報表示用コンポーネントの追加

## 期待する見せ方・挙動 / Expected behavior

- コンポーネントに長崎市の最新情報を表示する

## Link

https://data.bodik.jp/dataset/422011_corona03/resource/eb0ba50a-7a97-4029-9b75-9c6bab0568f6

## API
http://data.bodik.jp/api/action/datastore_search?resource_id=eb0ba50a-7a97-4029-9b75-9c6bab0568f6

**Comment by tkt989** [comment]
やります 🙋

**Comment by sugasaki** [comment]
おねがいします！！
