### ISSUE TITLE
最新のお知らせ欄へ長崎県2例目の感染者情報を表示する

### ISSUE THREAD

**Issue by nagasakisijohosystem** [CodeForNagasaki/covid19#51]
## 改善詳細 / Details of Improvement
長崎県で２例目となる新型コロナウイルス感染症の患者が出たので、最新のお知らせ欄に表示する
![最新感染動向](https://user-images.githubusercontent.com/62535540/77516171-3f69e400-6ebd-11ea-90ca-6ae98544977a.jpg)

## 期待する見せ方・挙動 / Expected behavior
・以下の通り表示をお願いします。
「2020/3/25　長崎県で2例目となる新型コロナウイルス感染症の感染者が確認さ れました。感染者は、県内の感染症指定医療機関で入院治療中です。」
・リンクの設定は、１例目と同様に長崎県HP「新型コロナウイルス感染症について（詳細情報）」
URL
https://www.pref.nagasaki.jp/bunrui/hukushi-hoken/kansensho/corona_nagasaki/corona_nagasaki_shousai/

**Comment by sugasaki** [comment]
@nagasakisijohosystem
対応完了しました！
