### ISSUE TITLE
flowの電話相談窓口の電話番号が異なっている

### ISSUE THREAD

**Issue by Nyoho** [CodeForNagasaki/covid19#63]
Slackの投稿から飛んできて見ていたら気付きましたのでご報告します!

## 起こっている問題 / The Problem
- flowページの電話相談窓口の電話番号が表示とリンクが異なっている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/118150/77970999-94c44c00-7328-11ea-87d7-7a99f875f1c0.png)

![image](https://user-images.githubusercontent.com/118150/77971006-99890000-7328-11ea-90b1-25bc11b3997a.png)

## 期待する見せ方・挙動 / Expected Behavior
- aタグのhref (tel) と表示されているテキストのどちらかに合わせる

**Comment by sugasaki** [comment]
@Nyoho 
今気付きました！ありがとうございます！

**Comment by Nyoho** [comment]
@sugasaki よかったです!

**Comment by kitadakyou** [comment]
@sugasaki こちら既に解決済みでしょうか…？

**Comment by Nyoho** [comment]
@kitadakyou 解決されているように見えますね。
![image](https://user-images.githubusercontent.com/118150/79032602-d4b9e780-7be2-11ea-8b64-9de86bf825f6.png)

**Comment by sugasaki** [comment]
@kitadakyou 
閉じるの忘れてました
クローズでします

@Nyoho 
確認ありがとうございますm(_ _)m
