### ISSUE TITLE
長崎市の窓口混雑情報へのリンクをサイドメニューに追加する

### ISSUE THREAD

**Issue by sugasaki** [CodeForNagasaki/covid19#81]
## 改善詳細 / Details of Improvement
- 長崎市地域センター窓口混雑情報へのリンクを追加する

https://www.city.nagasaki.lg.jp/shimin/121000/121100/p034298.html?fbclid=IwAR0H72wOgecIHlI8mKvrttq3XR93X7NPRppUbquW9QGzDAhWQ3UtwXDyftQ

**Comment by kitadakyou** [comment]
初めまして。
こちらの Issue を担当させて頂きたいです。

**Comment by kensukekanzaki** [comment]
ごめん、この内容pullしました。

**Comment by kitadakyou** [comment]
あっ…承知です。

**Comment by sugasaki** [comment]
@kitadakyou 
ありがとうございますm(_ _)m
書き込みに気づいてなくて申し訳ありません。
いろいろ足りてないので引き続き協力していただければありがたいです。

**Comment by sugasaki** [comment]
@kensukekanzaki 
ありがとうございます
